import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFile(resolve(root, path), 'utf8')

test('Architecture Foundation activates with six logical REQs', async () => {
  const backlog = await read('.rag/bba-platform/EXECUTION-BACKLOG.yaml')
  const graph = await read('.rag/bba-platform/dependency-graph.yaml')
  const source = await read('.rag/bba-platform/architecture/BBAPLT-ARCH-001-ARCHITECTURE-CONSTITUTION.md')
  assert.match(backlog, /id: "EPIC-003"[\s\S]*status: "IN_PROGRESS"[\s\S]*status_reason: "(ARCHITECTURE_ROLLOUT_ACTIVE|LOGICAL_INTERFACE_MODEL_ACTIVE|INTERACTION_ARCHITECTURE_ACTIVE)"/)
  assert.match(backlog, /id: "SPRINT-003-01"[\s\S]*status: "PASS_CLOSED"[\s\S]*status_reason: "ARCHITECTURE_FOUNDATION_PASS"/)
  for (const id of ['REQ-003-01-001', 'REQ-003-01-002', 'REQ-003-01-003', 'REQ-003-01-004', 'REQ-003-01-005', 'REQ-003-01-006']) {
    assert.match(backlog, new RegExp(`id: "${id}"`))
    assert.match(graph, new RegExp(`"${id}"`))
  }
  assert.match(backlog, /id: "REQ-003-01-001"[\s\S]*status: "DONE"/)
  assert.match(source, /document_id: "BBAPLT-ARCH-001"/)
  assert.match(source, /Architecture derives from Domain/)
  assert.match(source, /Domain derives from Product/)
  assert.match(source, /AI Workforce participates in bounded work and never owns final institutional authority/)
  assert.match(source, /does not select microservices,[\s\S]*monoliths,[\s\S]*event-driven[\s\S]*execution/)
  await access(resolve(root, '.rag/bba-platform/architecture/BBAPLT-ARCH-001-ARCHITECTURE-CONSTITUTION.md'))
  const context = await read('.rag/bba-platform/architecture/BBAPLT-ARCH-002-CANONICAL-SYSTEM-CONTEXT.md')
  assert.match(backlog, /id: "REQ-003-01-002"[\s\S]*status: "DONE"/)
  assert.match(context, /document_id: "BBAPLT-ARCH-002"/)
  for (const actor of ['Human Governance', 'AI Workforce', 'Mission', 'Institutional Asset', 'Workflow', 'Users', 'Organizations', 'External Platforms', 'External AI Providers', 'External Identity Providers', 'External Knowledge Sources']) assert.match(context, new RegExp(actor))
  assert.match(context, /does not prescribe[\s\S]*protocols, APIs, or infrastructure/)
  await access(resolve(root, '.rag/bba-platform/architecture/BBAPLT-ARCH-002-CANONICAL-SYSTEM-CONTEXT.md'))
  const contexts = await read('.rag/bba-platform/architecture/BBAPLT-ARCH-003-BOUNDED-CONTEXT-ARCHITECTURE.md')
  assert.match(backlog, /id: "REQ-003-01-003"[\s\S]*status: "DONE"/)
  assert.match(contexts, /document_id: "BBAPLT-ARCH-003"/)
  for (const term of ['Owner', 'Upstream', 'Downstream', 'Shared Kernel', 'Anti-Corruption Layer', 'Published Language', 'Conformist', 'Partnership']) assert.match(contexts, new RegExp(term))
  assert.match(contexts, /There is no Shared Kernel/)
  assert.match(contexts, /mandatory Anti-Corruption Layer/)
  assert.match(contexts, /not a service,[\s\S]*repository,[\s\S]*database,[\s\S]*process,[\s\S]*deployment unit,[\s\S]*framework[\s\S]*boundary/)
  await access(resolve(root, '.rag/bba-platform/architecture/BBAPLT-ARCH-003-BOUNDED-CONTEXT-ARCHITECTURE.md'))
  const components = await read('.rag/bba-platform/architecture/BBAPLT-ARCH-004-LOGICAL-COMPONENT-MODEL.md')
  assert.match(backlog, /id: "REQ-003-01-004"[\s\S]*status: "DONE"/)
  assert.match(components, /document_id: "BBAPLT-ARCH-004"/)
  for (const taxonomy of ['Core Components', 'Supporting Components', 'Coordination Components', 'Integration Components', 'Governance Components', 'Knowledge Components']) assert.match(components, new RegExp(taxonomy))
  assert.match(components, /## Dependency Rules/)
  assert.match(components, /Dependencies must be directional, explicit, and justified/)
  assert.match(components, /No dependency may create institutional authority for an Agent or Component/)
  assert.match(components, /not deployables,[\s\S]*code[\s\S]*packages,[\s\S]*services,[\s\S]*databases,[\s\S]*queues,[\s\S]*framework[\s\S]*modules/)
  await access(resolve(root, '.rag/bba-platform/architecture/BBAPLT-ARCH-004-LOGICAL-COMPONENT-MODEL.md'))
  const flow = await read('.rag/bba-platform/architecture/BBAPLT-ARCH-005-CANONICAL-INFORMATION-FLOW.md')
  assert.match(backlog, /id: "REQ-003-01-005"[\s\S]*status: "DONE"/)
  assert.match(flow, /document_id: "BBAPLT-ARCH-005"/)
  assert.match(flow, /Information Ownership/)
  assert.match(flow, /Information State Changes/)
  assert.match(flow, /semantic information flow/)
  assert.match(flow, /does not prescribe[\s\S]*(transport|API|event|queue|persistence)/i)
  await access(resolve(root, '.rag/bba-platform/architecture/BBAPLT-ARCH-005-CANONICAL-INFORMATION-FLOW.md'))
  const glossary = await read('.rag/bba-platform/architecture/BBAPLT-ARCH-006-ARCHITECTURE-GLOSSARY-AND-TAXONOMY.md')
  assert.match(backlog, /id: "REQ-003-01-006"[\s\S]*status: "DONE"/)
  assert.match(backlog, /id: "SPRINT-003-01"[\s\S]*status: "PASS_CLOSED"[\s\S]*status_reason: "ARCHITECTURE_FOUNDATION_PASS"/)
  assert.match(glossary, /document_id: "BBAPLT-ARCH-006"/)
  assert.match(glossary, /Architecture Glossary/)
  for (const term of ['Component', 'Context', 'Boundary', 'Interface', 'Dependency', 'Contract', 'Information Flow', 'Capability Mapping', 'Responsibility', 'Coordination']) assert.match(glossary, new RegExp(`\\b${term}\\b`))
  for (const taxonomy of ['Core Components', 'Supporting Components', 'Coordination Components', 'Integration Components', 'Governance Components', 'Knowledge Components']) assert.match(glossary, new RegExp(taxonomy))
  assert.match(glossary, /does not replace Domain language/)
  assert.match(glossary, /not an API[\s\S]*not a runtime[\s\S]*not a deployment mechanism/i)
  await access(resolve(root, '.rag/bba-platform/architecture/BBAPLT-ARCH-006-ARCHITECTURE-GLOSSARY-AND-TAXONOMY.md'))
})
