import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFile(resolve(root, path), 'utf8')

test('Connector Sprint closes with thirteen ordered REQs and a Workflow dependency', async () => {
  const backlog = await read('.rag/bba-platform/EXECUTION-BACKLOG.yaml')
  const graph = await read('.rag/bba-platform/dependency-graph.yaml')
  assert.match(backlog, /id: "SPRINT-002-06"[\s\S]*status: "PASS_CLOSED"/)
  assert.match(backlog, /status_reason: "CONNECTOR_CANONICAL_REVIEW_PASS"/)
  for (const id of ['REQ-002-06-001', 'REQ-002-06-002', 'REQ-002-06-003', 'REQ-002-06-004', 'REQ-002-06-005', 'REQ-002-06-006', 'REQ-002-06-007', 'REQ-002-06-008', 'REQ-002-06-009', 'REQ-002-06-010', 'REQ-002-06-011', 'REQ-002-06-012', 'REQ-002-06-013']) {
    assert.match(backlog, new RegExp(`id: "${id}"`))
    assert.match(graph, new RegExp(`"${id}"`))
  }
  assert.match(graph, /from: "SPRINT-002-06"\n    to: "SPRINT-002-05"\n    type: "DEPENDS_ON"/)
  await access(resolve(root, '.rag/bba-platform/domain/BBAPLT-GDE-064-CONNECTOR-DOMAIN-OVERVIEW.md'))
})

test('Connector Overview defines a semantic boundary without technical integration leakage', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-064-CONNECTOR-DOMAIN-OVERVIEW.md')
  assert.match(source, /document_id: "BBAPLT-GDE-064"/)
  assert.match(source, /A Connector is a boundary concept/)
  for (const concept of ['Mission', 'Institutional Asset', 'AI Workforce', 'Workflow', 'Human Governance', 'Tenant']) assert.match(source, new RegExp(`\\| ${concept} \\|`))
  assert.match(source, /Connector is not an API,[\s\S]*protocol,[\s\S]*webhook,[\s\S]*queue/)
  assert.match(source, /preserving Asset identity,[\s\S]*lineage,[\s\S]*version meaning,[\s\S]*authority/)
  assert.match(source, /never creates[\s\S]*institutional Authority,[\s\S]*changes Rules,[\s\S]*alters Accountability/)
  assert.match(source, /does not define APIs,[\s\S]*protocols,[\s\S]*authentication,[\s\S]*runtime/)
})

test('Connector identity and classifications remain semantic and technology-independent', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-065-CONNECTOR-IDENTITY-AND-CLASSIFICATION.md')
  assert.match(source, /document_id: "BBAPLT-GDE-065"/)
  assert.match(source, /stable semantic relationship and boundary role/)
  for (const classification of ['Inbound', 'Outbound', 'Bidirectional', 'Human-mediated', 'Automated', 'Institutional']) assert.match(source, new RegExp(`\\| ${classification} \\|`))
  assert.match(source, /does not depend on an external vendor,[\s\S]*URL,[\s\S]*endpoint,[\s\S]*protocol/)
  assert.match(source, /Classifications describe semantic roles/)
  assert.match(source, /not[\s\S]*protocols,[\s\S]*deployment modes,[\s\S]*trust scores/)
  assert.match(source, /A Connector retains its canonical identity across representations,[\s\S]*executors/)
  assert.match(source, /Classification cannot enlarge the Connector's responsibility,[\s\S]*authority,[\s\S]*Mission scope/)
  assert.match(source, /does not define identifiers,[\s\S]*schemas,[\s\S]*endpoints,[\s\S]*API contracts/)
})

test('Connector responsibilities preserve authority, identity, accountability, and boundary scope', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-066-CONNECTOR-RESPONSIBILITIES.md')
  assert.match(source, /document_id: "BBAPLT-GDE-066"/)
  for (const responsibility of ['Receive external requests', 'Deliver institutional results', 'Forward information', 'Preserve context', 'Translate meaning', 'Surface exceptions']) assert.match(source, new RegExp(`\\| ${responsibility} \\|`))
  assert.match(source, /do not execute[\s\S]*institutional decision[\s\S]*represented by the exchange/)
  assert.match(source, /Connector never:/)
  assert.match(source, /changes a domain Rule/)
  assert.match(source, /creates institutional Authority/)
  assert.match(source, /creates, closes, cancels/)
  assert.match(source, /changes Institutional Asset identity,[\s\S]*Ownership,[\s\S]*lineage,[\s\S]*publication authority/)
  assert.match(source, /changes Workflow semantics,[\s\S]*bypasses a Guard,[\s\S]*removes a human gate/)
  assert.match(source, /institutional Accountability remains with the competent human role/)
  assert.match(source, /does not define request handlers,[\s\S]*message delivery,[\s\S]*APIs,[\s\S]*protocols/)
})

test('Connector Boundary Model preserves Domain, External, Trust, and Tenant boundaries', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-067-BOUNDARY-MODEL.md')
  assert.match(source, /document_id: "BBAPLT-GDE-067"/)
  for (const boundary of ['Domain Boundary', 'External Boundary', 'Trust Boundary', 'Tenant Boundary']) assert.match(source, new RegExp(`\\| ${boundary} \\|`))
  assert.match(source, /does not erase a boundary when it exchanges context/)
  assert.match(source, /preserves the source, destination,[\s\S]*Tenant,[\s\S]*Mission,[\s\S]*Asset,[\s\S]*authority,[\s\S]*uncertainty/)
  assert.match(source, /cannot decide that a boundary is irrelevant,[\s\S]*transfer Authority by implication/)
  assert.match(source, /one Tenant's Authority,[\s\S]*Assets,[\s\S]*Mission[\s\S]*purpose,[\s\S]*Accountability cannot be transferred/)
  assert.match(source, /ambiguous origin,[\s\S]*missing Tenant,[\s\S]*unrecognized authority,[\s\S]*boundary bypass blocks or escalates/)
  assert.match(source, /does not define network zones,[\s\S]*firewalls,[\s\S]*encryption,[\s\S]*identity[\s\S]*providers/)
})

test('Connector Context and Translation preserve canonical meaning and disclose semantic loss', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-068-CONTEXT-AND-TRANSLATION-MODEL.md')
  assert.match(source, /document_id: "BBAPLT-GDE-068"/)
  for (const element of ['Source context', 'Target context', 'Canonical representation', 'Transformation', 'Semantic loss', 'Consequence']) assert.match(source, new RegExp(`\\| ${element} \\|`))
  assert.match(source, /cannot[\s\S]*silently change institutional purpose,[\s\S]*Asset identity,[\s\S]*lineage,[\s\S]*Authority,[\s\S]*Mission scope/)
  assert.match(source, /Canonical representation is a domain meaning,[\s\S]*not a file format,[\s\S]*schema,[\s\S]*API[\s\S]*payload/)
  assert.match(source, /Semantic loss is any material meaning that is omitted,[\s\S]*ambiguous,[\s\S]*weakened/)
  assert.match(source, /must be disclosed and may[\s\S]*block a Decision Point,[\s\S]*require human Review,[\s\S]*Escalation/)
  assert.match(source, /preserves Asset identity and lineage[\s\S]*Mission[\s\S]*context,[\s\S]*Tenant boundary,[\s\S]*Accountability/)
  assert.match(source, /does not define schemas,[\s\S]*field mappings,[\s\S]*serializers,[\s\S]*APIs,[\s\S]*protocols/)
})

test('Connector lifecycle preserves governance, history, and boundary meaning', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-069-CONNECTOR-LIFECYCLE.md')
  assert.match(source, /document_id: "BBAPLT-GDE-069"/)
  for (const state of ['Proposed', 'Active', 'Restricted', 'Suspended', 'Retired']) assert.match(source, new RegExp(`\\| ${state} \\|`))
  assert.match(source, /not a process status,[\s\S]*health signal,[\s\S]*deployment state,[\s\S]*runtime condition/)
  assert.match(source, /Every lifecycle decision identifies the Connector identity,[\s\S]*Tenant,[\s\S]*external relationship,[\s\S]*Accountability/)
  assert.match(source, /Activation[\s\S]*requires a defined boundary/)
  assert.match(source, /accountable human[\s\S]*role/)
  assert.match(source, /canonical[\s\S]*context, applicable Rules/)
  assert.match(source, /Retirement prevents new exchanges but preserves lineage,[\s\S]*decisions,[\s\S]*accountability/)
  assert.match(source, /An Agent, Workflow,[\s\S]*cannot activate,[\s\S]*restrict,[\s\S]*suspend, or retire/)
  assert.match(source, /does not define service health,[\s\S]*deployment,[\s\S]*connection state,[\s\S]*monitoring/)
})

test('Connector State Model defines guarded semantic movement and terminal retirement', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-070-CONNECTOR-STATE-MODEL.md')
  assert.match(source, /document_id: "BBAPLT-GDE-070"/)
  for (const state of ['Unassessed', 'Ready', 'Operating', 'Degraded', 'Blocked', 'Awaiting Decision', 'Retired']) assert.match(source, new RegExp(`\\| ${state} \\|`))
  for (const transition of ['Unassessed → Ready', 'Ready → Operating', 'Operating → Degraded', 'Operating → Blocked', 'Degraded → Awaiting Decision', 'Blocked → Ready', 'Any non-terminal → Retired']) assert.match(source, new RegExp(`\\| ${transition} \\|`))
  assert.match(source, /State describes the current semantic condition[\s\S]*does not describe process health,[\s\S]*technical availability/)
  assert.match(source, /Retired is terminal for new Connector exchanges/)
  assert.match(source, /Reactivation is not an[\s\S]*implicit reversal;[\s\S]*requires a new assessment/)
  assert.match(source, /technical availability/)
  assert.match(source, /Agent recommendation/)
  assert.match(source, /Workflow[\s\S]*readiness[\s\S]*cannot satisfy a semantic Guard/)
  assert.match(source, /does not define state machines,[\s\S]*events,[\s\S]*status[\s\S]*codes,[\s\S]*health[\s\S]*checks/)
})

test('Connector Interaction Model references established domains without controlling them', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-071-INTERACTION-MODEL.md')
  assert.match(source, /document_id: "BBAPLT-GDE-071"/)
  for (const domain of ['Mission', 'Institutional Asset', 'AI Workforce', 'Workflow', 'Human Governance']) assert.match(source, new RegExp(`\\| ${domain} \\|`))
  assert.match(source, /participates in a domain interaction by carrying bounded context/)
  assert.match(source, /Every interaction preserves:/)
  for (const concept of ['Connector identity', 'Tenant and Mission context', 'Asset identity', 'Authority', 'evidence', 'applicable Rule']) assert.match(source, new RegExp(concept))
  assert.match(source, /does not transfer ownership[\s\S]*interaction's purpose,[\s\S]*authority,[\s\S]*accountability/)
  assert.match(source, /never makes an external party an Agent,[\s\S]*Steward,[\s\S]*Approver,[\s\S]*Authority/)
  assert.match(source, /does not define interaction protocols,[\s\S]*message[\s\S]*contracts,[\s\S]*API[\s\S]*operations,[\s\S]*event choreography/)
})

test('Connector Rules preserve identity, lineage, authority, accountability, Tenant, and Mission boundaries', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-072-CONNECTOR-RULES.md')
  assert.match(source, /document_id: "BBAPLT-GDE-072"/)
  assert.match(source, /Connector identity remains distinct from external systems,[\s\S]*Assets,[\s\S]*Missions,[\s\S]*Agents/)
  assert.match(source, /preserves Institutional Asset[\s\S]*identity,[\s\S]*lineage,[\s\S]*immutable version[\s\S]*meaning/)
  assert.match(source, /preserves Mission purpose,[\s\S]*scope,[\s\S]*lifecycle,[\s\S]*accountability/)
  assert.match(source, /never creates,[\s\S]*transfers/)
  assert.match(source, /institutional[\s\S]*Authority/)
  assert.match(source, /preserves Tenant Boundary[\s\S]*cannot share one Tenant's context/)
  assert.match(source, /cannot bypass Workflow Guards,[\s\S]*human gates,[\s\S]*Reviews,[\s\S]*Approvals/)
  assert.match(source, /discloses semantic loss,[\s\S]*uncertainty,[\s\S]*conflict,[\s\S]*risk/)
  assert.match(source, /does not define rule engines,[\s\S]*authorization,[\s\S]*access control,[\s\S]*APIs,[\s\S]*protocols/)
})

test('Connector Policies govern exposure and sharing without weakening Rules', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-073-CONNECTOR-POLICIES.md')
  assert.match(source, /document_id: "BBAPLT-GDE-073"/)
  for (const area of ['Exposure', 'Sharing', 'Semantic synchronization', 'Reuse', 'Institutional authorization', 'Publication restriction']) assert.match(source, new RegExp(`\\| ${area} \\|`))
  assert.match(source, /Every Policy declares scope,[\s\S]*purpose,[\s\S]*owner,[\s\S]*effective context/)
  assert.match(source, /absence[\s\S]*of a Policy[\s\S]*not permission to cross a boundary[\s\S]*expose an Asset/)
  assert.match(source, /Connector Rules have precedence over Policies/)
  assert.match(source, /cannot weaken a[\s\S]*Rule,[\s\S]*create Authority,[\s\S]*transfer Accountability,[\s\S]*change Asset identity/)
  assert.match(source, /Policy changes are prospective[\s\S]*do not silently rewrite historical exchanges/)
  assert.match(source, /does not define policy engines/)
  assert.match(source, /configuration,[\s\S]*authorization[\s\S]*matrices/)
  assert.match(source, /APIs,[\s\S]*protocols/)
})

test('Connector Constraints protect Tenant, authority, meaning, lineage, governance, and trust', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-074-CONNECTOR-CONSTRAINTS.md')
  assert.match(source, /document_id: "BBAPLT-GDE-074"/)
  for (const constraint of ['Tenant isolation', 'Authority preservation', 'Semantic integrity', 'Lineage preservation', 'Governance compliance', 'Trust boundary', 'Mission scope', 'Publication boundary', 'Evidence', 'Accountability']) assert.match(source, new RegExp(`\\| ${constraint} \\|`))
  assert.match(source, /A Connector cannot expose,[\s\S]*one Tenant's context,[\s\S]*another Tenant/)
  assert.match(source, /cannot create,[\s\S]*expand,[\s\S]*transfer,[\s\S]*institutional Authority/)
  assert.match(source, /must preserve canonical meaning or disclose material semantic loss,[\s\S]*ambiguity,[\s\S]*uncertainty/)
  assert.match(source, /Every Asset representation,[\s\S]*retains the originating Asset and relationship lineage/)
  assert.match(source, /cannot enlarge,[\s\S]*create, cancel, or complete a Mission/)
  assert.match(source, /cannot be hidden by a successful technical transfer,[\s\S]*retry,[\s\S]*replacement executor/)
  assert.match(source, /does not define network isolation,[\s\S]*encryption,[\s\S]*quotas,[\s\S]*authorization enforcement/)
})

test('Connector interaction matrix preserves ownership across all established domains', async () => {
  const source = await read('.rag/bba-platform/domain/BBAPLT-GDE-075-CROSS-DOMAIN-INTERACTION-MATRIX.md')
  assert.match(source, /document_id: "BBAPLT-GDE-075"/)
  for (const domain of ['Mission', 'Institutional Asset', 'AI Workforce', 'Human Governance', 'Workflow']) assert.match(source, new RegExp(`\\| ${domain} \\|`))
  assert.match(source, /Mission owns purpose,[\s\S]*scope,[\s\S]*lifecycle,[\s\S]*Steward/)
  assert.match(source, /Asset Domain owns identity,[\s\S]*lineage,[\s\S]*versions,[\s\S]*publication meaning/)
  assert.match(source, /AI Workforce owns Agent,[\s\S]*Capability,[\s\S]*Assignment,[\s\S]*Responsibility/)
  assert.match(source, /Human Governance owns institutional Authority,[\s\S]*Approval,[\s\S]*Stewardship,[\s\S]*Accountability/)
  assert.match(source, /Workflow owns coordination,[\s\S]*Criteria,[\s\S]*Guards,[\s\S]*Transitions/)
  assert.match(source, /Connector participation is a relationship to a domain,[\s\S]*not ownership of that[\s\S]*domain/)
  assert.match(source, /does not define integration topology,[\s\S]*APIs,[\s\S]*protocols,[\s\S]*events,[\s\S]*queues/)
})

test('Connector Domain review closes the Sprint and hands off to EPIC canonical review', async () => {
  const backlog = await read('.rag/bba-platform/EXECUTION-BACKLOG.yaml')
  const review = await read('.rag/bba-platform/domain/BBAPLT-RPT-010-CONNECTOR-DOMAIN-REVIEW.md')
  assert.match(backlog, /id: "EPIC-002"[\s\S]*status: "PASS_CLOSED"[\s\S]*status_reason: "DOMAIN_CANONICAL_REVIEW_PASS"/)
  for (const id of ['REQ-002-06-001', 'REQ-002-06-002', 'REQ-002-06-003', 'REQ-002-06-004', 'REQ-002-06-005', 'REQ-002-06-006', 'REQ-002-06-007', 'REQ-002-06-008', 'REQ-002-06-009', 'REQ-002-06-010', 'REQ-002-06-011', 'REQ-002-06-012', 'REQ-002-06-013']) assert.match(backlog, new RegExp(`id: "${id}"[\\s\\S]*status: "DONE"`))
  assert.match(backlog, /id: "SPRINT-002-06"[\s\S]*status: "PASS_CLOSED"[\s\S]*status_reason: "CONNECTOR_CANONICAL_REVIEW_PASS"/)
  assert.match(review, /document_id: "BBAPLT-RPT-010"/)
  assert.match(review, /PASS — Connector Domain is coherent/)
  assert.match(review, /Cross-Domain Consistency/)
  assert.match(review, /Boundary Verification/)
  assert.match(review, /Technical Boundary Verification/)
  assert.match(review, /Known Gaps and Future Decisions/)
  assert.match(review, /Domain Rollout Canonical Review/)
})
